using System;
using System.Linq;
using System.Windows.Forms;

namespace ChaipiaInventoryProgram
{
    public class HistoryForm : Form
        {
                private DateTimePicker _from;
                        private DateTimePicker _to;
                                private DataGridView _grid;
                                        private Label _summary;

                                                public HistoryForm()
                                                        {
                                                                    Text = "History";
                                                                                Width = 900;
                                                                                            Height = 500;
                                                                                                        StartPosition = FormStartPosition.CenterParent;

                                                                                                                    var topPanel = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 40 };
                                                                                                                                topPanel.Controls.Add(new Label { Text = "From:", AutoSize = true, TextAlign = System.Drawing.ContentAlignment.MiddleCenter });
                                                                                                                                            _from = new DateTimePicker { Format = DateTimePickerFormat.Custom, CustomFormat = "dd/MM/yyyy" };
                                                                                                                                                        topPanel.Controls.Add(_from);
                                                                                                                                                                    topPanel.Controls.Add(new Label { Text = "To:", AutoSize = true });
                                                                                                                                                                                _to = new DateTimePicker { Format = DateTimePickerFormat.Custom, CustomFormat = "dd/MM/yyyy" };
                                                                                                                                                                                            topPanel.Controls.Add(_to);

                                                                                                                                                                                                        var btnRefresh = new Button { Text = "Refresh" };
                                                                                                                                                                                                                    btnRefresh.Click += (_, __) => LoadHistory();
                                                                                                                                                                                                                                topPanel.Controls.Add(btnRefresh);

                                                                                                                                                                                                                                            _grid = new DataGridView
                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                        Dock = DockStyle.Fill,
                                                                                                                                                                                                                                                                                        AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill,
                                                                                                                                                                                                                                                                                                        AllowUserToAddRows = false
                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                _summary = new Label
                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                            Dock = DockStyle.Bottom,
                                                                                                                                                                                                                                                                                                                                                                            Height = 30,
                                                                                                                                                                                                                                                                                                                                                                                            TextAlign = System.Drawing.ContentAlignment.MiddleLeft
                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                    Controls.Add(_grid);
                                                                                                                                                                                                                                                                                                                                                                                                                                Controls.Add(_summary);
                                                                                                                                                                                                                                                                                                                                                                                                                                            Controls.Add(topPanel);

                                                                                                                                                                                                                                                                                                                                                                                                                                                        _from.Value = DateTime.Today.AddMonths(-1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _to.Value = DateTime.Today;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LoadHistory();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private void LoadHistory()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var all = Utils.LoadHistory();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var filtered = all.Where(r => r.Date.Date >= _from.Value.Date && r.Date.Date <= _to.Value.Date).ToList();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _grid.DataSource = filtered;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var totalIn = filtered.Sum(r => r.StockIn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var totalOut = filtered.Sum(r => r.StockOut);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var totalAmount = filtered.Sum(r => r.LineAmount);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _summary.Text = $"In: {totalIn}   Out: {totalOut}   Amount: {totalAmount:C}";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }