using System;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

namespace ChaipiaInventoryProgram
{
    public class MainForm : Form
        {
                private TabControl tabs;
                        private DataGridView gridGeneral;
                                private DataGridView gridToiletries;

                                        public MainForm()
                                                {
                                                            Text = "Chaipia Inventory Program";
                                                                        Width = 900;
                                                                                    Height = 600;
                                                                                                StartPosition = FormStartPosition.CenterScreen;

                                                                                                            tabs = new TabControl { Dock = DockStyle.Fill };

                                                                                                                        var tabGeneral = new TabPage("General");
                                                                                                                                    gridGeneral = CreateInventoryGrid();
                                                                                                                                                tabGeneral.Controls.Add(CreatePanelWithButtons(gridGeneral, "General"));
                                                                                                                                                            tabs.TabPages.Add(tabGeneral);

                                                                                                                                                                        var tabToiletries = new TabPage("Toiletries");
                                                                                                                                                                                    gridToiletries = CreateInventoryGrid();
                                                                                                                                                                                                tabToiletries.Controls.Add(CreatePanelWithButtons(gridToiletries, "Toiletries"));
                                                                                                                                                                                                            tabs.TabPages.Add(tabToiletries);

                                                                                                                                                                                                                        Controls.Add(tabs);

                                                                                                                                                                                                                                    LoadData();
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                    private void LoadData()
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                        gridGeneral.DataSource = Utils.LoadInventory("General");
                                                                                                                                                                                                                                                                                    gridToiletries.DataSource = Utils.LoadInventory("Toiletries");
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                    private Panel CreatePanelWithButtons(DataGridView grid, string category)
                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                        var panel = new Panel { Dock = DockStyle.Fill };

                                                                                                                                                                                                                                                                                                                                    var topPanel = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 40 };
                                                                                                                                                                                                                                                                                                                                                var btnAdd = new Button { Text = "Add Item" };
                                                                                                                                                                                                                                                                                                                                                            var btnDelete = new Button { Text = "Delete Item" };
                                                                                                                                                                                                                                                                                                                                                                        var btnSave = new Button { Text = "Save Changes" };
                                                                                                                                                                                                                                                                                                                                                                                    var btnHistory = new Button { Text = "History" };
                                                                                                                                                                                                                                                                                                                                                                                                var btnPrint = new Button { Text = "Print Preview" };

                                                                                                                                                                                                                                                                                                                                                                                                            btnAdd.Click += (_, __) =>
                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                        var list = grid.DataSource as List<Item>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        list?.Add(new Item { Name = "New Item", Quantity = 0, CurrentPrice = 0 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        grid.Refresh();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btnDelete.Click += (_, __) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            foreach (DataGridViewRow row in grid.SelectedRows)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                grid.Rows.Remove(row);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        btnSave.Click += (_, __) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var list = grid.DataSource as List<Item>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (list != null) Utils.SaveInventory(category, list);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btnHistory.Click += (_, __) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new HistoryForm().ShowDialog();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btnPrint.Click += (_, __) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var list = grid.DataSource as List<Item>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (list != null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                new PrintPreviewForm(category, list).ShowDialog();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        topPanel.Controls.AddRange(new Control[] { btnAdd, btnDelete, btnSave, btnHistory, btnPrint });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    panel.Controls.Add(grid);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                panel.Controls.Add(topPanel);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return panel;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private DataGridView CreateInventoryGrid()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var grid = new DataGridView
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dock = DockStyle.Fill,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            AllowUserToAddRows = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return grid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }