using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;

namespace ChaipiaInventoryProgram
{
    public class PrintPreviewForm : Form
        {
                private readonly string _category;
                        private readonly List<Item> _items;
                                private PrintDocument _doc;

                                        public PrintPreviewForm(string category, List<Item> items)
                                                {
                                                            _category = category;
                                                                        _items = items;

                                                                                    Text = "Print Preview - " + category;
                                                                                                Width = 900;
                                                                                                            Height = 600;
                                                                                                                        StartPosition = FormStartPosition.CenterParent;

                                                                                                                                    _doc = new PrintDocument();
                                                                                                                                                _doc.PrintPage += Doc_PrintPage;

                                                                                                                                                            var preview = new PrintPreviewControl
                                                                                                                                                                        {
                                                                                                                                                                                        Dock = DockStyle.Fill,
                                                                                                                                                                                                        Document = _doc,
                                                                                                                                                                                                                        Zoom = 1.0
                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                Controls.Add(preview);
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                private void Doc_PrintPage(object sender, PrintPageEventArgs e)
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                    var g = e.Graphics;
                                                                                                                                                                                                                                                                                                var font = new Font("Arial", 10);
                                                                                                                                                                                                                                                                                                            var y = 50;

                                                                                                                                                                                                                                                                                                                        g.DrawString("Inventory - " + _category, new Font("Arial", 14, FontStyle.Bold), Brushes.Black, 50, y);
                                                                                                                                                                                                                                                                                                                                    y += 40;

                                                                                                                                                                                                                                                                                                                                                g.DrawLine(Pens.Black, 50, y, 750, y);
                                                                                                                                                                                                                                                                                                                                                            y += 10;

                                                                                                                                                                                                                                                                                                                                                                        g.DrawString("Name", font, Brushes.Black, 50, y);
                                                                                                                                                                                                                                                                                                                                                                                    g.DrawString("Qty", font, Brushes.Black, 300, y);
                                                                                                                                                                                                                                                                                                                                                                                                g.DrawString("Price", font, Brushes.Black, 400, y);
                                                                                                                                                                                                                                                                                                                                                                                                            g.DrawString("Remarks", font, Brushes.Black, 500, y);

                                                                                                                                                                                                                                                                                                                                                                                                                        y += 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                    g.DrawLine(Pens.Black, 50, y, 750, y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                y += 10;

                                                                                                                                                                                                                                                                                                                                                                                                                                                            foreach (var item in _items)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        g.DrawString(item.Name, font, Brushes.Black, 50, y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        g.DrawString(item.Quantity.ToString(), font, Brushes.Black, 300, y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        g.DrawString(item.CurrentPrice.ToString("C"), font, Brushes.Black, 400, y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        g.DrawString(item.Remarks, font, Brushes.Black, 500, y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        y += 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                g.DrawLine(Pens.Black, 50, y, 750, y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }